name: tajiri_ai
description: An AI based financial tracker and an advisory provider aimed for personal and small business use.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.0
  firebase_storage: ^11.7.5
  firebase_app_check: ^0.2.2+1
  google_sign_in: ^6.2.1

  # State Management
  provider: ^6.1.2

  # UI & Design
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  intl: ^0.19.0

  # Functionality
  image_picker: ^1.1.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png