name: tajiri_ai
description: An AI based financial tracker and an advisory provider aimed for personal and small business use.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  cloud_functions:
  firebase_storage:
  google_sign_in:

  # State Management
  provider: ^6.1.2

  # UI & Design
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  intl: ^0.20.2

  # Functionality
  image_picker: ^1.1.2
  logging: ^1.3.0
  rxdart: ^0.28.0
  firebase_app_check: ^0.3.2+7
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png