// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVw8C3LhZ4_SwZVbV2hcOB4rOe2kYaVG4',
    appId: '1:670998225121:web:89e1da57ee3c6322b057a0',
    messagingSenderId: '670998225121',
    projectId: 'tajiri-ai-v1',
    authDomain: 'tajiri-ai-v1.firebaseapp.com',
    storageBucket: 'tajiri-ai-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOiO23VrQfo4PgS4l6XJc4kEBsIO2H68k',
    appId: '1:143364800780:android:4d46d8e8d7f5ea9d000929',
    messagingSenderId: '143364800780',
    projectId: 'tajiri-ai-dev',
    storageBucket: 'tajiri-ai-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbWfgwv6anTbrMuwovnx_N_4wTfdNlPA8',
    appId: '1:670998225121:ios:8a46b582d17614c9b057a0',
    messagingSenderId: '670998225121',
    projectId: 'tajiri-ai-v1',
    storageBucket: 'tajiri-ai-v1.firebasestorage.app',
    iosBundleId: 'com.example.tajiriAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbWfgwv6anTbrMuwovnx_N_4wTfdNlPA8',
    appId: '1:670998225121:ios:8a46b582d17614c9b057a0',
    messagingSenderId: '670998225121',
    projectId: 'tajiri-ai-v1',
    storageBucket: 'tajiri-ai-v1.firebasestorage.app',
    iosBundleId: 'com.example.tajiriAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVw8C3LhZ4_SwZVbV2hcOB4rOe2kYaVG4',
    appId: '1:670998225121:web:aa88db885603fd11b057a0',
    messagingSenderId: '670998225121',
    projectId: 'tajiri-ai-v1',
    authDomain: 'tajiri-ai-v1.firebaseapp.com',
    storageBucket: 'tajiri-ai-v1.firebasestorage.app',
  );
}