// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-wFvrOo2csO9N4EbFdeFe6xezJufVZ0',
    appId: '1:143364800780:web:fc499e67fa6ffcdc000929',
    messagingSenderId: '143364800780',
    projectId: 'tajiri-ai-dev',
    authDomain: 'tajiri-ai-dev.firebaseapp.com',
    storageBucket: 'tajiri-ai-dev.firebasestorage.app',
    measurementId: 'G-J8R0H36MNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOiO23VrQfo4PgS4l6XJc4kEBsIO2H68k',
    appId: '1:143364800780:android:ad967a3440acc380000929',
    messagingSenderId: '143364800780',
    projectId: 'tajiri-ai-dev',
    storageBucket: 'tajiri-ai-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWuRTeB6L-BF3HVTI4f0Lq_-7B34Bs7g',
    appId: '1:143364800780:ios:d93a47b1b2abb73e000929',
    messagingSenderId: '143364800780',
    projectId: 'tajiri-ai-dev',
    storageBucket: 'tajiri-ai-dev.firebasestorage.app',
    iosBundleId: 'com.example.tajiriAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWuRTeB6L-BF3HVTI4f0Lq_-7B34Bs7g',
    appId: '1:143364800780:ios:d93a47b1b2abb73e000929',
    messagingSenderId: '143364800780',
    projectId: 'tajiri-ai-dev',
    storageBucket: 'tajiri-ai-dev.firebasestorage.app',
    iosBundleId: 'com.example.tajiriAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7-wFvrOo2csO9N4EbFdeFe6xezJufVZ0',
    appId: '1:143364800780:web:de46876de5b56753000929',
    messagingSenderId: '143364800780',
    projectId: 'tajiri-ai-dev',
    authDomain: 'tajiri-ai-dev.firebaseapp.com',
    storageBucket: 'tajiri-ai-dev.firebasestorage.app',
    measurementId: 'G-5BD3ZVCNE5',
  );
}
